### PR TITLE
add a test for #17

### PR DESCRIPTION
**Pull request by ocefpaf**
This reproduces #17 dowe can start to address it.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks, it definitely reproduces the issue, boggling.

**Comment by akrherz** [comment]
continues to fail, shucks
```
+ wgrib2 file.grib2 -netcdf out.nc
libpng error: bad parameters to zlib

*** FATAL ERROR: unpk: png decode error -3 ***
```

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Oh wow, no longer reproducing

```
  wgrib2 file.grib2 -netcdf out.nc
1:0:d=2020120523:var discipline=209 center=161 local_table=1 parmcat=11 parm=3:500 m above mean sea level:anl:type_reftime=observation time
** Warning: reference time includes non-zero minutes/seconds **
 exit 0
```

**Review by akrherz — APPROVED** [review]

**Comment by ocefpaf** [comment]
This PR was almost as old as my child ;-p

**Pull request merged**
